version: '2.0'
services:
    spark-master:
        image: spark-master:v1.0
        hostname: spark-master
        environment:
            - SPARK_PUBLIC_DNS=10.1.1.1
        networks:
            - cluster_network
        ports:
            - 6066:6066
            - 7077:7077
            - 8080:8080
            - 18080:18080
        volumes:
            - /mnt/data/spark:/workspace/data/spark
    spark-worker-1:
        image: spark-worker:v1.0
        hostname: worker
        environment:
            - SPARK_PUBLIC_DNS=10.1.1.1
        depends_on:
            - spark-master
        networks:
            - cluster_network
        ports:
            - 8081:8081
        volumes:
            - /mnt/data/spark:/workspace/data/spark
    spark-worker-2:
      image: spark-worker:v1.0
      hostname: worker
      environment:
        - SPARK_PUBLIC_DNS=10.1.1.1
      depends_on:
        - spark-master
      networks:
        - cluster_network
      ports:
        - 8082:8081
      volumes:
        - /mnt/data/spark:/workspace/data/spark
networks:
    cluster_network:
        ipam:
            driver: default
            config:
                - subnet: 10.20.30.0/24